services:
  postgres:
    image: postgres
    container_name: katocheck_postgres
    environment:
      POSTGRES_USER: katocheck
      POSTGRES_PASSWORD: katocheck
      POSTGRES_DB: katocheck
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: